import { LOCALES } from "./locales";

export const messages = {
    [LOCALES.ENGLISH]: {
        about: "About",
        aboutDescription:
            "The Computer Science + Social Good club at the University of Delaware thrives as a dynamic hub where cutting-edge technology converges with a deep commitment to societal betterment. Within the vibrant campus ecosystem, this club embodies a shared vision of using computer science as a driving force for positive change. Through a blend of innovative projects, engaging discussions, and collaborative events, the club's members delve into the transformative potential of technology to address pressing global challenges. From developing applications that enhance accessibility for differently-abled individuals to creating digital platforms that amplify underrepresented voices, the club serves as a crucible of ideas that embody the principles of social responsibility, inclusivity, and ethical innovation. By fostering a space where interdisciplinary collaboration flourishes, the Computer Science + Social Good club at the University of Delaware not only shapes the technologists of tomorrow but also embodies the institution's commitment to fostering engaged and conscientious citizens. As a vital component of the University of Delaware's campus fabric, the Computer Science + Social Good club takes its commitment beyond theoretical discourse, translating ideas into tangible actions that have a lasting impact on both local and global communities. Through strategic partnerships with local non-profits, startups, and community organizations, the club creates avenues for its members to apply their technical expertise to real-world challenges. Workshops that bridge computer science with issues like environmental sustainability, healthcare accessibility, and educational equity provide a launchpad for students to harness their skills for the greater good. The club's collaborative ethos and its emphasis on meaningful projects that serve the community mirror the University of Delaware's ethos of innovation with a purpose. As the club continues to innovate and evolve, it remains a testament to the University's dedication to nurturing socially conscious leaders who harness technology to create positive, transformative change.",
        aboutTheClub: "About The Club",
        cssgDescription:
            "Our mission is to foster interest in applying technical knowledge and experience in ways that will help our community and promote technology as a means for positive social change. We plan to connect students with organizations in our community that promote social good, such as non-profits and philanthropic organizations, in order to work on technical projects that help these organizations achieve their goals. We will also provide students with resources needed to assist in these projects. Members of this organization, both computer science majors and non-majors, will develop their design thinking skills and learn how to apply their knowledge to real-world problems. Students who attend our speaker events will learn about current social issues in technology and beyond, and also think critically about what they can do to address these issues. We must start by changing the conversation around technology toward positive social impact, and then we must translate that conversation into action.",
        eboard: "EBoard",
        eboardMembers: "EBoard Members",
        events: "Events",
        faq: "FAQ",
        faqDescription: "For more questions regarding the cs+sg club, we are happy to answer them!",
        home: "Home",
        homePageTooltip: "Home Page",
        presidentDescription:
            "Meet Diya Shah, an exceptional co-president driving the Computer Science + Social Good club's mission at our college. With a strong commitment to leveraging technology for positive change, Diya seamlessly merges her technical acumen with a profound passion for societal betterment. Her strategic vision and collaborative spirit empower the club to explore innovative ways in which computer science can address pressing global challenges. Through her leadership, Diya inspires members to harness their skills for social impact, making a tangible difference within our campus community and beyond.",
        projectOutreachDescription:
        "Meet Sneha Nangelimalil, the dedicated Volunteer Outreach Chair of the Computer Science + Social Good club at our college. With an unwavering commitment to community engagement and a passion for making a difference, Sneha plays a pivotal role in mobilizing volunteers for impactful projects. Her exceptional interpersonal skills and empathetic nature enable her to connect with individuals and organizations alike, fostering partnerships that drive positive change. Through Sneha's leadership, the club's outreach efforts extend beyond the campus, creating opportunities for members to channel their enthusiasm for computer science into meaningful acts of social good.",
        secretaryDescription:
            "Introducing Benita Abraham, the capable Secretary of the Computer Science + Social Good club at our college. With meticulous attention to detail and a passion for effective communication, Benita keeps the club's operations running smoothly. Her organizational prowess ensures that meetings, events, and vital information are seamlessly managed, enabling the club to focus on its mission of using technology for positive social impact. Benita's dedication to facilitating collaboration and transparent communication is integral to fostering a vibrant community of aspiring changemakers within the club.",
        socialMediaDescription:
            "Introducing Charmaine Pasicolan, the dynamic Social Media Manager of the Computer Science + Social Good club at our college. With a creative flair and a strategic approach, Charmaine spearheads the club's online presence, effectively amplifying its mission and impact. Her skillful management of various platforms ensures that the club's initiatives, events, and achievements reach a wider audience, inspiring engagement and participation. Charmaine's ability to harness the digital landscape for social good helps cultivate a vibrant online community, uniting like-minded individuals dedicated to using technology for positive change.",
        treasurerDescription:
            "Meet Matt Weis, the astute Treasurer of the Computer Science + Social Good club at our college. With a keen eye for financial management and a passion for promoting positive change, Matt plays a crucial role in ensuring the club's financial stability. His meticulous record-keeping and budgeting skills enable the club to effectively allocate resources to meaningful projects that align with our mission. Matt's commitment to transparency and fiscal responsibility empowers the club to maximize its impact in combining technology with social good, fostering a community where innovation and financial prudence go hand in hand.",
        vicePresidentDescription:
            "Meet Donovan Messer, the dedicated Vice President of the Computer Science + Social Good club at our college. With a passion for both technology and social responsibility, Donovan plays a pivotal role in shaping the club's initiatives. His analytical mindset and strong organizational skills ensure the seamless execution of projects that harness the power of computer science to drive positive societal change. Donovan's collaborative spirit and drive inspire members to actively engage in meaningful discussions and hands-on projects that make a lasting impact within our campus and beyond.",
        volunteerOutreachChairDescription:
            "Introducing Maxwell Wang, the dedicated Volunteer Outreach Chair of the Computer Science + Social Good club at our college. With a passion for community engagement and a strategic approach, Maxwell takes the lead in connecting the club with opportunities for meaningful impact. His adept communication skills and proactive attitude enable him to forge partnerships with local organizations, amplifying the club's reach and influence. Maxwell's commitment to channeling the club's technical expertise into acts of social good inspires members to actively participate in initiatives that make a tangible difference, both on campus and in the broader community.",
        welcomeMessage: "Welcome to UD CS + Social Good",
    },
    [LOCALES.FRENCH]: {
        about: "À propos",
        aboutDescription:
            "Le club Computer Science + Social Good de l'Université du Delaware se développe comme un centre dynamique où la technologie de pointe converge avec un engagement profond envers l'amélioration de la société. Au sein de l'écosystème dynamique du campus, ce club incarne une vision partagée de l'utilisation de l'informatique comme moteur de changement positif. Grâce à un mélange de projets innovants, de discussions engageantes et d'événements collaboratifs, les membres du club explorent le potentiel de transformation de la technologie pour relever les défis mondiaux urgents. Du développement d'applications qui améliorent l'accessibilité pour les personnes handicapées à la création de plateformes numériques qui amplifient les voix sous-représentées, le club sert de creuset d'idées qui incarnent les principes de responsabilité sociale, d'inclusivité et d'innovation éthique. En favorisant un espace où la collaboration interdisciplinaire s'épanouit, le club Computer Science + Social Good de l'Université du Delaware façonne non seulement les technologues de demain, mais incarne également l'engagement de l'institution à favoriser des citoyens engagés et consciencieux. En tant que composante essentielle du tissu du campus de l'Université du Delaware, le club Computer Science + Social Good va au-delà du discours théorique, traduisant les idées en actions tangibles qui ont un impact durable sur les communautés locales et mondiales. Grâce à des partenariats stratégiques avec des organisations à but non lucratif, des startups et des organisations communautaires locales, le club crée des possibilités pour ses membres d'appliquer leur expertise technique aux défis du monde réel. Les ateliers qui relient l'informatique à des questions telles que la durabilité environnementale, l'accessibilité aux soins de santé et l'équité en matière d'éducation fournissent une rampe de lancement permettant aux étudiants d'exploiter leurs compétences pour le plus grand bien. La philosophie de collaboration du club et l'accent mis sur des projets significatifs qui servent la communauté reflètent la philosophie d'innovation de l'Université du Delaware avec un but. Alors que le club continue d'innover et d'évoluer, il reste un témoignage du dévouement de l'Université à former des leaders socialement responsables qui exploitent la technologie pour créer un changement positif et transformateur.",
        aboutTheClub: "À propos du club",
        cssgDescription:
            "Notre mission est de susciter l'intérêt pour l'application des connaissances et de l'expérience techniques de manière à aider notre communauté et à promouvoir la technologie comme moyen de changement social positif. Nous prévoyons de connecter les étudiants avec des organisations de notre communauté qui promeuvent le bien social, telles que des organisations à but non lucratif et philanthropiques, afin de travailler sur des projets techniques qui aident ces organisations à atteindre leurs objectifs. Nous fournirons également aux étudiants les ressources nécessaires pour les aider dans ces projets. Les membres de cette organisation, qu'ils soient spécialisés ou non en informatique, développeront leurs compétences en matière de réflexion conceptuelle et apprendront à appliquer leurs connaissances à des problèmes du monde réel. Les étudiants qui assistent à nos événements de conférenciers découvriront les problèmes sociaux actuels dans le domaine de la technologie et au-delà, et réfléchiront également de manière critique à ce qu'ils peuvent faire pour résoudre ces problèmes. Nous devons commencer par changer la conversation autour de la technologie vers un impact social positif, puis nous devons traduire cette conversation en action.",
        eboard: "Tableau électronique",
        eboardMembers: "Membres du conseil électronique",
        events: "Événements",
        faq: "FAQ",
        faqDescription: "Pour plus de questions concernant le club cs+sg, nous serons ravis d'y répondre ",
        home: "Maison",
        homePageTooltip: "Page d'accueil",
        presidentDescription: "Rencontrez Diya Shah, une co-présidente exceptionnelle qui dirige la mission du club Computer Science + Social Good de notre collège. Avec un engagement fort à tirer parti de la technologie pour un changement positif, Diya fusionne de manière transparente son sens technique avec une profonde passion pour l'amélioration de la société. Sa vision stratégique et son esprit de collaboration permettent au club d'explorer des moyens innovants par lesquels l'informatique peut relever des défis mondiaux urgents. Grâce à son leadership, Diya inspire les membres à exploiter leurs compétences pour un impact social, faisant une différence tangible au sein de la communauté de notre campus et au-delà.",
        projectOutreachDescription: "Rencontrez Sneha Nangelimalil, la responsable de la sensibilisation des bénévoles du club Computer Science + Social Good de notre collège. Avec un engagement inébranlable envers l'engagement communautaire et une passion pour faire une différence, Sneha joue un rôle central dans la mobilisation de bénévoles pour des projets percutants. Ses compétences interpersonnelles exceptionnelles et sa nature empathique lui permettent de se connecter avec des individus et des organisations, favorisant des partenariats qui entraînent des changements positifs. Grâce au leadership de Sneha, les efforts de sensibilisation du club s'étendent au-delà du campus, créant des opportunités pour les membres de canaliser leur enthousiasme pour l'informatique en actes significatifs de bien social.",
        secretaryDescription:
            "Présentation de Benita Abraham, la secrétaire compétente du club Informatique + Bien social de notre collège. Avec une attention méticuleuse aux détails et une passion pour une communication efficace, Benita assure le bon fonctionnement des opérations du club. Ses prouesses organisationnelles garantissent que les réunions, les événements et les informations vitales sont gérés de manière transparente, permettant au club de se concentrer sur sa mission d'utiliser la technologie pour un impact social positif. Le dévouement de Benita à faciliter la collaboration et la communication transparente fait partie intégrante de la promotion d'une communauté dynamique d'aspirants acteurs du changement au sein du club.",
        socialMediaDescription:
            "Voici Charmaine Pasicolan, la dynamique Social Media Manager du club Computer Science + Social Good de notre collège. Avec un flair créatif et une approche stratégique, Charmaine est le fer de lance de la présence en ligne du club, amplifiant efficacement sa mission et son impact. Sa gestion habile de diverses plateformes garantit que les initiatives, les événements et les réalisations du club atteignent un public plus large, inspirant l'engagement et la participation. La capacité de Charmaine à exploiter le paysage numérique pour le bien social aide à cultiver une communauté en ligne dynamique, réunissant des personnes partageant les mêmes idées et dédiées à l'utilisation de la technologie pour un changement positif.",
        treasurerDescription:
            "Rencontrez Matt Weis, l'astucieux trésorier du club Computer Science + Social Good de notre collège. Avec un sens aigu de la gestion financière et une passion pour la promotion de changements positifs, Matt joue un rôle crucial pour assurer la stabilité financière du club. Ses compétences méticuleuses en matière de tenue de dossiers et de budgétisation permettent au club d'allouer efficacement des ressources à des projets significatifs qui correspondent à notre mission. L'engagement de Matt envers la transparence et la responsabilité financière permet au club de maximiser son impact en combinant la technologie avec le bien social, en favorisant une communauté où l'innovation et la prudence financière vont de pair.",
        vicePresidentDescription:
            "Rencontrez Donovan Messer, le vice-président dévoué du club Computer Science + Social Good de notre collège. Passionné à la fois de technologie et de responsabilité sociale, Donovan joue un rôle central dans l'élaboration des initiatives du club. Son esprit d'analyse et ses solides compétences organisationnelles garantissent l'exécution transparente de projets qui exploitent la puissance de l'informatique pour conduire un changement sociétal positif. L'esprit de collaboration et le dynamisme de Donovan incitent les membres à s'engager activement dans des discussions significatives et des projets pratiques qui ont un impact durable sur notre campus et au-delà.",
        volunteerOutreachChairDescription:
            "Présentation de Maxwell Wang, le responsable de la sensibilisation des bénévoles du club Computer Science + Social Good de notre collège. Avec une passion pour l'engagement communautaire et une approche stratégique, Maxwell prend l'initiative de connecter le club avec des opportunités d'impact significatif. Ses compétences en communication et son attitude proactive lui permettent de forger des partenariats avec des organisations locales, amplifiant la portée et l'influence du club. L'engagement de Maxwell à canaliser l'expertise technique du club dans des actes de bien social incite les membres à participer activement à des initiatives qui font une différence tangible, à la fois sur le campus et dans la communauté au sens large.",
        welcomeMessage: "Bienvenue sur UD CS + Bien Social",
    },
    [LOCALES.SPANISH]: {
        about: "Sobre Nosotros",
        aboutDescription:
            "El club Computer Science + Social Good de la Universidad de Delaware prospera como un centro dinámico donde la tecnología de vanguardia converge con un profundo compromiso con la mejora social. Dentro del vibrante ecosistema del campus, este club encarna una visión compartida de utilizar la informática como fuerza impulsora para un cambio positivo. A través de una combinación de proyectos innovadores, discusiones interesantes y eventos de colaboración, los miembros del club profundizan en el potencial transformador de la tecnología para abordar los desafíos globales apremiantes. Desde el desarrollo de aplicaciones que mejoran la accesibilidad para personas con capacidades diferentes hasta la creación de plataformas digitales que amplifican las voces subrepresentadas, el club sirve como un crisol de ideas que encarnan los principios de responsabilidad social, inclusión e innovación ética. Al fomentar un espacio donde florece la colaboración interdisciplinaria, el club Computer Science + Social Good de la Universidad de Delaware no solo da forma a los tecnólogos del mañana, sino que también encarna el compromiso de la institución de fomentar ciudadanos comprometidos y conscientes. Como componente vital del tejido del campus de la Universidad de Delaware, el club Computer Science + Social Good lleva su compromiso más allá del discurso teórico, traduciendo ideas en acciones tangibles que tienen un impacto duradero en las comunidades locales y globales. A través de asociaciones estratégicas con organizaciones locales sin fines de lucro, nuevas empresas y organizaciones comunitarias, el club crea vías para que sus miembros apliquen su experiencia técnica a los desafíos del mundo real. Los talleres que unen la informática con temas como la sostenibilidad ambiental, la accesibilidad a la atención médica y la equidad educativa brindan una plataforma de lanzamiento para que los estudiantes aprovechen sus habilidades para el bien común. El espíritu colaborativo del club y su énfasis en proyectos significativos que sirvan a la comunidad reflejan el espíritu de innovación con un propósito de la Universidad de Delaware. A medida que el club continúa innovando y evolucionando, sigue siendo un testimonio de la dedicación de la Universidad para fomentar líderes socialmente conscientes que aprovechan la tecnología para crear un cambio positivo y transformador.",
        aboutTheClub: "Sobre El Club",
        cssgDescription:
            "Nuestra misión es fomentar el interés en aplicar el conocimiento técnico y la experiencia de manera que ayude a nuestra comunidad y promueva la tecnología como un medio para el cambio social positivo. Planeamos conectar a los estudiantes con organizaciones en nuestra comunidad que promuevan el bien social, como organizaciones filantrópicas y sin fines de lucro, para trabajar en proyectos técnicos que ayuden a estas organizaciones a lograr sus objetivos. También proporcionaremos a los estudiantes los recursos necesarios para ayudar en estos proyectos. Los miembros de esta organización, tanto con especialización en ciencias de la computación como sin ella, desarrollarán sus habilidades de pensamiento de diseño y aprenderán a aplicar sus conocimientos a problemas del mundo real. Los estudiantes que asistan a nuestros eventos de oradores aprenderán sobre problemas sociales actuales en tecnología y más allá, y también pensarán críticamente sobre lo que pueden hacer para abordar estos problemas. Debemos comenzar cambiando la conversación en torno a la tecnología hacia un impacto social positivo, y luego debemos traducir esa conversación en acción.",
        eboard: "Tablero electrónico",
        eboardMembers: "Miembros de la junta electrónica",
        events: "Eventos",
        faq: "Preguntas más frecuentes",
        faqDescription: "Si tienes más preguntas sobre el club cs+sg, ¡estaremos encantados de responderlas!",
        home: "Hogar",
        homePageTooltip: "Página de inicio",
        presidentDescription: "Conozca a Diya Shah, un copresidente excepcional que impulsa la misión del club Computer Science + Social Good en nuestra universidad. Con un fuerte compromiso de aprovechar la tecnología para un cambio positivo, Diya fusiona a la perfección su perspicacia técnica con una profunda pasión por el mejoramiento de la sociedad. Su visión estratégica y espíritu colaborativo capacitan al club para explorar formas innovadoras en las que la informática puede abordar desafíos globales apremiantes. A través de su liderazgo, Diya inspira a los miembros a aprovechar sus habilidades para lograr un impacto social, marcando una diferencia tangible dentro de la comunidad de nuestro campus y más allá.",
        projectOutreachDescription: "Conozca a Sneha Nangelimalil, la dedicada directora de divulgación voluntaria del club Computer Science + Social Good de nuestra universidad. Con un compromiso inquebrantable con la participación de la comunidad y una pasión por marcar la diferencia, Sneha desempeña un papel fundamental en la movilización de voluntarios para proyectos impactantes. Sus habilidades interpersonales excepcionales y su naturaleza empática le permiten conectarse con individuos y organizaciones por igual, fomentando asociaciones que impulsan un cambio positivo. A través del liderazgo de Sneha, los esfuerzos de divulgación del club se extienden más allá del campus, creando oportunidades para que los miembros canalicen su entusiasmo por la informática en actos significativos de bien social.",
        secretaryDescription:
            "Presentamos a Benita Abraham, la competente Secretaria del club Computer Science + Social Good de nuestra universidad. Con una atención meticulosa a los detalles y una pasión por la comunicación efectiva, Benita mantiene las operaciones del club funcionando sin problemas. Su destreza organizativa garantiza que las reuniones, los eventos y la información vital se gestionen sin problemas, lo que permite que el club se centre en su misión de utilizar la tecnología para lograr un impacto social positivo. La dedicación de Benita para facilitar la colaboración y la comunicación transparente es fundamental para fomentar una comunidad vibrante de aspirantes a agentes de cambio dentro del club.",
        socialMediaDescription:
            "Presentamos a Charmaine Pasicolan, la dinámica administradora de redes sociales del club Computer Science + Social Good de nuestra universidad. Con un estilo creativo y un enfoque estratégico, Charmaine encabeza la presencia en línea del club, amplificando efectivamente su misión e impacto. Su hábil gestión de varias plataformas garantiza que las iniciativas, los eventos y los logros del club lleguen a un público más amplio, lo que inspira el compromiso y la participación. La capacidad de Charmaine para aprovechar el panorama digital para el bien social ayuda a cultivar una comunidad en línea vibrante, uniendo a personas con ideas afines dedicadas al uso de la tecnología para un cambio positivo.",
        treasurerDescription:
            "Conozca a Matt Weis, el astuto tesorero del club Computer Science + Social Good de nuestra universidad. Con un buen ojo para la gestión financiera y una pasión por promover un cambio positivo, Matt desempeña un papel crucial para garantizar la estabilidad financiera del club. Sus meticulosas habilidades de mantenimiento de registros y presupuestos permiten al club asignar recursos de manera efectiva a proyectos significativos que se alinean con nuestra misión. El compromiso de Matt con la transparencia y la responsabilidad fiscal le permite al club maximizar su impacto al combinar la tecnología con el bien social, fomentando una comunidad donde la innovación y la prudencia financiera van de la mano.",
        vicePresidentDescription:
            "Conozca a Donovan Messer, el vicepresidente dedicado del club Computer Science + Social Good de nuestra universidad. Con una pasión tanto por la tecnología como por la responsabilidad social, Donovan desempeña un papel fundamental en la configuración de las iniciativas del club. Su mentalidad analítica y sus sólidas habilidades organizativas garantizan la ejecución perfecta de proyectos que aprovechan el poder de la informática para impulsar un cambio social positivo. El espíritu colaborativo y el impulso de Donovan inspiran a los miembros a participar activamente en discusiones significativas y proyectos prácticos que tienen un impacto duradero dentro de nuestro campus y más allá.",
        volunteerOutreachChairDescription:
            "Presentamos a Maxwell Wang, el dedicado presidente de divulgación voluntaria del club Computer Science + Social Good de nuestra universidad. Con una pasión por la participación de la comunidad y un enfoque estratégico, Maxwell toma la iniciativa para conectar el club con oportunidades de impacto significativo. Sus hábiles habilidades de comunicación y su actitud proactiva le permiten forjar alianzas con organizaciones locales, lo que amplía el alcance y la influencia del club. El compromiso de Maxwell de canalizar la experiencia técnica del club en actos de bien social inspira a los miembros a participar activamente en iniciativas que marcan una diferencia tangible, tanto en el campus como en la comunidad en general.",
        welcomeMessage: "Bienvenidos a UD CS + Bien Social",
    },
};
